# Generated by Django 3.2.9 on 2021-11-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_alter_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('root', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(default='Automation policy description', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('root', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(default='Template description', max_length=512)),
                ('value', models.TextField()),
                ('variables', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('automation_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.automationpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAutomationPolicyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('root', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(unique=True)),
                ('automation_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.automationpolicy')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.template')),
            ],
            options={
                'unique_together': {('template', 'automation_policy')},
            },
        ),
        migrations.CreateModel(
            name='GroupAutomationPolicyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('root', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(unique=True)),
                ('automation_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.automationpolicy')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.group')),
            ],
            options={
                'unique_together': {('group', 'automation_policy')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAutomationPolicyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('root', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(unique=True)),
                ('automation_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.automationpolicy')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
            options={
                'unique_together': {('device', 'automation_policy')},
            },
        ),
    ]
