# Generated by Django 3.2.9 on 2021-11-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211126_2141'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
            preserve_default=False,
        ),
    ]
