# Generated by Django 3.2.9 on 2021-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcredentialrelation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colorcredentialrelation',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colordevicerelation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colordevicerelation',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colorgrouprelation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colorgrouprelation',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupdevicerelation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupdevicerelation',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
