# Generated by Django 3.2.9 on 2021-11-19 22:28

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211119_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(error_messages={'blank': 'This field is mandatory.', 'invalid': 'Enter the correct colour value. It must be a 3/6 hexadecimal number with # character on begining', 'null': 'This field is mandatory.'}, help_text='Hexadecimal representation of colour, for example #73a6ff.', max_length=7, unique=True, validators=[inventory.validators.ColorValueValidator()]),
        ),
    ]
