# Generated by Django 3.2.9 on 2021-11-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_color_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='colorcredentialrelation',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.color'),
        ),
        migrations.AlterField(
            model_name='colorcredentialrelation',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.credential'),
        ),
        migrations.AlterField(
            model_name='colordevicerelation',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.color'),
        ),
        migrations.AlterField(
            model_name='colordevicerelation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
        ),
        migrations.AlterField(
            model_name='colorgrouprelation',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.color'),
        ),
        migrations.AlterField(
            model_name='colorgrouprelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.group'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(default='Device description.', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'autodetect'), (1, 'cisco_ios'), (2, 'cisco_xr'), (3, 'cisco_xe'), (4, 'cisco_nxos')], default=0, verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(error_messages={'blank': 'This field is mandatory.', 'null': 'This field is mandatory.'}, help_text='Enter a valid IP address or DNS resolvable hostname.', max_length=64, unique=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='https_port',
            field=models.IntegerField(default=443, verbose_name='HTTPS port'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ico',
            field=models.IntegerField(choices=[(0, 'static/ico/model/device/switch.svg'), (1, 'static/ico/model/device/border_router.svg'), (2, 'static/ico/model/device/chassis.svg'), (3, 'static/ico/model/device/console.svg'), (4, 'static/ico/model/device/firewall.svg'), (5, 'static/ico/model/device/router.svg'), (6, 'static/ico/model/device/router_firewall.svg'), (7, 'static/ico/model/device/router_wifi_1.svg'), (8, 'static/ico/model/device/router_wifi_2.svg'), (9, 'static/ico/model/device/stack.svg'), (10, 'static/ico/model/device/stack_firewall_1.svg'), (11, 'static/ico/model/device/stack_firewall_2.svg'), (12, 'static/ico/model/device/switch.svg'), (13, 'static/ico/model/device/wifi-connection.svg'), (14, 'static/ico/model/device/wireless-router.svg')], default=0, verbose_name='Device graphic'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='SSH port'),
        ),
    ]
