# Generated by Django 3.2.9 on 2021-11-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211125_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('hostname', models.CharField(blank=True, max_length=64, null=True)),
                ('uptime', models.CharField(blank=True, max_length=64, null=True)),
                ('reload_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('running_image', models.CharField(blank=True, max_length=64, null=True)),
                ('config_register', models.CharField(blank=True, max_length=64, null=True)),
                ('hardware_list', models.JSONField(blank=True, null=True)),
                ('serial_list', models.JSONField(blank=True, null=True)),
                ('mac_list', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
    ]
