# Generated by Django 3.2.9 on 2021-11-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.CharField(default='Credentials description.', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Credential name'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='User password'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(max_length=64, verbose_name='User name'),
        ),
    ]
